# a basic configuration file for the Text Editor application

# Set default values for the application
default:
  # set the default font for the application
  textFormat: "Monospaced"
  # set the default font size for the application
  fontSize: 14
  # set the default font color for the application
  fontColor: "blue"

